- name: Montar Card e Enviar ao Teams
  hosts: localhost
  gather_facts: yes

  vars:
    webhook_url: "SUA_WEBHOOK_URL"

  tasks:

    - name: Garantir que HEALTHCHECK existe
      set_fact:
        HEALTHCHECK: "{{ HEALTHCHECK | default([]) }}"

    - name: Exibir tudo que veio dos playbooks anteriores
      debug:
        var: HEALTHCHECK

    - name: Montar dynamic_facts unificado de forma genérica
      set_fact:
        dynamic_facts: >
          {{
            HEALTHCHECK | map('combine', {'title': item.title, 'value': item.value}) | list
          }}

    - name: Renderizar o modelo do Adaptive Card
      template:
        src: templates/adaptive_card.json.j2
        dest: /tmp/card.json

    - name: Enviar ao Teams
      uri:
        url: "{{ webhook_url }}"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body: "{{ lookup('file', '/tmp/card.json') | from_json }}"
