---
- name: Health Check Dynatrace – Infra, Application e Services
  hosts: localhost
  gather_facts: no

  vars:
    dynatrace_url: "{{DT_TENANT_URL}}"   # Ex: https://abc123.live.dynatrace.com
    dynatrace_token: "{{DT_API_TOKEN}}" # Token com scope: metrics.read, entities.read, problems.read

    # IDs ou tags do tenant a verificar
    infra_tag: "INFRA"
    app_tag: "APP"
    service_tag: "SERVICE"

  tasks:

    - name: Validar variáveis obrigatórias
      fail:
        msg: "dynatrace_url ou dynatrace_token não configurados."
      when: dynatrace_url == "" or dynatrace_token == ""

    #################################################################
    # 1) HEALTH INFRA  
    #################################################################
    - name: Consultar Infraestrutura com tag
      uri:
        url: "{{ dynatrace_url }}/api/v2/entities"
        method: GET
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
        return_content: yes
        status_code: 200
        validate_certs: yes
        params:
          entitySelector: "type(HOST),tag({{ infra_tag }})"
      register: infra_response

    - name: Processar saúde dos hosts
      set_fact:
        infra_health: "{{ (infra_response.json.items | map(attribute='healthState') | list) }}"

    #################################################################
    # 2) HEALTH APPLICATION
    #################################################################
    - name: Consultar Aplicações com tag
      uri:
        url: "{{ dynatrace_url }}/api/v2/entities"
        method: GET
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
        return_content: yes
        status_code: 200
        validate_certs: yes
        params:
          entitySelector: "type(APPLICATION),tag({{ app_tag }})"
      register: app_response

    - name: Processar saúde das aplicações
      set_fact:
        app_health: "{{ (app_response.json.items | map(attribute='healthState') | list) }}"

    #################################################################
    # 3) HEALTH SERVICES
    #################################################################
    - name: Consultar Serviços com tag
      uri:
        url: "{{ dynatrace_url }}/api/v2/entities"
        method: GET
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
        return_content: yes
        status_code: 200
        validate_certs: yes
        params:
          entitySelector: "type(SERVICE),tag({{ service_tag }})"
      register: service_response

    - name: Processar saúde dos serviços
      set_fact:
        service_health: "{{ (service_response.json.items | map(attribute='healthState') | list) }}"

    #################################################################
    # 4) CHECAR PROBLEMAS ABERTOS
    #################################################################
    - name: Consultar problemas abertos no Dynatrace
      uri:
        url: "{{ dynatrace_url }}/api/v2/problems"
        method: GET
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
        return_content: yes
        status_code: 200
        validate_certs: yes
      register: problems_response

    - name: Processar problemas abertos
      set_fact:
        open_problems: "{{ problems_response.json.totalCount }}"

    #################################################################
    # 5) SUMMARY FINAL
    #################################################################
    - name: Gerar Summary do Health Check
      set_fact:
        health_summary: |
          🔍 **Health Check Dynatrace**
          ---
          🖥 **Infraestrutura (Hosts com tag {{ infra_tag }})**
          Statuses: {{ infra_health }}

          🌐 **Aplicações (tag {{ app_tag }})**
          Statuses: {{ app_health }}

          🔧 **Serviços (tag {{ service_tag }})**
          Statuses: {{ service_health }}

          🚨 **Problemas Abertos:** {{ open_problems }}

    - name: Exibir Summary Final
      debug:
        msg: "{{ health_summary }}"
