---
- name: Health Check Dynatrace – Infra, Application e Services
  hosts: localhost
  gather_facts: no

  vars:
    dynatrace_url: "{{ DT_TENANT_URL }}"
    dynatrace_token: "{{ DT_API_TOKEN }}"

    infra_tag: "INFRA"
    app_tag: "APP"
    service_tag: "SERVICE"

  tasks:

    - name: Validar variáveis obrigatórias
      fail:
        msg: "dynatrace_url ou dynatrace_token não configurados."
      when: dynatrace_url == "" or dynatrace_token == ""

    #################################################################
    # 1) HEALTH INFRA  
    #################################################################
    - name: Consultar Infraestrutura com tag
      uri:
        url: "{{ dynatrace_url }}/api/v2/entities?entitySelector=type(HOST),tag({{ infra_tag }})"
        method: GET
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
        return_content: yes
        status_code: 200
        validate_certs: yes
      register: infra_response

    - name: Processar saúde dos hosts (JSON completo)
      set_fact:
        infra_health: "{{ infra_response.json }}"

    #################################################################
    # 2) HEALTH APPLICATION
    #################################################################
    - name: Consultar Aplicações com tag
      uri:
        url: "{{ dynatrace_url }}/api/v2/entities?entitySelector=type(APPLICATION),tag({{ app_tag }})"
        method: GET
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
        return_content: yes
        status_code: 200
        validate_certs: yes
      register: app_response

    - name: Processar saúde das aplicações (JSON completo)
      set_fact:
        app_health: "{{ app_response.json }}"

    #################################################################
    # 3) HEALTH SERVICES
    #################################################################
    - name: Consultar Serviços com tag
      uri:
        url: "{{ dynatrace_url }}/api/v2/entities?entitySelector=type(SERVICE),tag({{ service_tag }})"
        method: GET
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
        return_content: yes
        status_code: 200
        validate_certs: yes
      register: service_response

    - name: Processar saúde dos serviços (JSON completo)
      set_fact:
        service_health: "{{ service_response.json }}"

    #################################################################
    # 4) CHECAR PROBLEMAS ABERTOS
    #################################################################
    - name: Consultar problemas abertos no Dynatrace
      uri:
        url: "{{ dynatrace_url }}/api/v2/problems"
        method: GET
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
        return_content: yes
        status_code: 200
        validate_certs: yes
      register: problems_response

    - name: Processar problemas abertos
      set_fact:
        open_problems: "{{ problems_response.json }}"

    #################################################################
    # 5) SUMMARY FINAL
    #################################################################
    - name: Gerar Summary do Health Check
      set_fact:
        health_summary: |
          🔍 **Health Check Dynatrace**
          ---
          🖥 **Infraestrutura (Hosts com tag {{ infra_tag }})**
          {{ infra_health }}

          🌐 **Aplicações (tag {{ app_tag }})**
          {{ app_health }}

          🔧 **Serviços (tag {{ service_tag }})**
          {{ service_health }}

          🚨 **Problemas Abertos (JSON):**
          {{ open_problems }}

    - name: Exibir Summary Final
      debug:
        msg: "{{ health_summary }}"
