---
- name: Healthcheck Dynatrace – Output estruturado
  hosts: localhost
  gather_facts: false

  vars:
    dt_tenant_url: "{{ lookup('env', 'DT_TENANT_URL') }}"
    dt_api_token: "{{ lookup('env', 'DT_API_TOKEN') }}"
    entity_selector: "type(HOST),tag(INFRA)"

  tasks:

    - name: Validar tenant e token
    - fail:
        msg: "Erro: DT_TENANT_URL ou DT_API_TOKEN não configurados."
      when: dt_tenant_url is undefined or dt_tenant_url == "" or
            dt_api_token is undefined or dt_api_token == ""

    - name: Buscar hosts no Dynatrace (v2/entities)
      uri:
        url: "{{ dt_tenant_url }}/api/v2/entities?entitySelector={{ entity_selector }}&pageSize=500"
        method: GET
        headers:
          Authorization: "Api-Token {{ dt_api_token }}"
        return_content: yes
        status_code: 200
        validate_certs: yes
      register: hosts_response

    - name: Extrair lista de entidades
      set_fact:
        lista_hosts: "{{ hosts_response.json.entities | default([]) }}"

    - name: Buscar health de cada host
      loop: "{{ lista_hosts }}"
      loop_control:
        loop_var: hostitem
      uri:
        url: "{{ dt_tenant_url }}/api/v2/entities/{{ hostitem.entityId }}/details"
        method: GET
        headers:
          Authorization: "Api-Token {{ dt_api_token }}"
        return_content: yes
        status_code: 200
        validate_certs: yes
      register: detalhes_host
      failed_when: false

    - name: Montar saída no formato estruturado
      set_fact:
        health_output: >-
          {{
            lista_hosts | map(
              lambda h: {
                "entityId": h.entityId,
                "displayName": h.displayName,
                "health": "OK" if (detalhes_host.results | selectattr('item.entityId', 'equalto', h.entityId) | list)[0].json.properties.availabilityState == "AVAILABLE"
                else "PROBLEM"
              }
            ) | list
          }}

    - name: Exibir Healthcheck Final
      debug:
        msg:
          hosts: "{{ health_output }}"
