- name: IIS
  hosts: all
  tasks:
    - name: Registrar healthcheck via set_stats
      set_stats:
        data:
          HEALTHCHECK_IIS:
            - title: "IIS"
              value: "OK"
    - name: IIS              
      debug:
        msg:
          {
            "DIAGNÓSTICO": [
              {
                "SERVIDOR": {
                  "HOST": "cadop-mqcrpw004.crefisa.com.br",
                  "ESTADO": "UP",
                  "UPTIME": "46 dias",
                  "CPU": "NORMAL < 90% (42%)",
                  "MEMÓRIA": "NORMAL < 90% (32.22%)",
                  "DISCO": [
                    "- C:: OK (44% Livre)",
                    "- D:: OK (86% Livre)"
                  ]
                }
              }
            ]
          }
