- name: Montar Card e Enviar ao Teams
  hosts: localhost
  gather_facts: yes

  vars:
    webhook_url: "https://accenture.webhook.office.com/webhookb2/e1bb6d1a-9f00-47c4-8da4-70c117755d54@e0793d39-0939-496d-b129-198edd916feb/IncomingWebhook/a94a253a2c4841558717eb921d9bf3d5/5bf8e6bb-735b-45d9-859a-867da2417df4/V2MboRW3qA0UjjLu2zRLT7KfIN-Fzl6N469UEEdYFR9NE1"

 tasks:

    - name: Capturar todas as variáveis do workflow
      set_fact:
        all_vars: "{{ hostvars['localhost'] | dict2items }}"

    - name: Filtrar apenas as healthchecks
      set_fact:
        healthcheck_lists: >-
          {{
            all_vars
            | selectattr('key', 'search', '^HEALTHCHECK_')
            | map(attribute='value')
            | list
          }}

    - name: Concatenar todos os healthchecks
      set_fact:
        HEALTHCHECK: "{{ healthcheck_lists | sum(start=[]) }}"

    - name: Exibir HEALTHCHECK final
      debug:
        var: HEALTHCHECK
    - name: Renderizar o modelo do Adaptive Card
      template:
        src: templates/adaptive_card_healthcheck.json.j2
        dest: /tmp/adaptive_card_healthcheck.json

    - name: Enviar ao Teams
      uri:
        url: "{{ webhook_url }}"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body: "{{ lookup('file', '/tmp/adaptive_card_healthcheck.json') | from_json }}"
