- name: Montar Card e Enviar ao Teams
  hosts: localhost
  gather_facts: yes

  vars:
    webhook_url: "https://accenture.webhook.office.com/webhookb2/e1bb6d1a-9f00-47c4-8da4-70c117755d54@e0793d39-0939-496d-b129-198edd916feb/IncomingWebhook/a94a253a2c4841558717eb921d9bf3d5/5bf8e6bb-735b-45d9-859a-867da2417df4/V2MboRW3qA0UjjLu2zRLT7KfIN-Fzl6N469UEEdYFR9NE1"

  tasks:

    - name: Garantir que HEALTHCHECK existe
      set_stats:
        HEALTHCHECK: "{{ HEALTHCHECK | default([]) }}"

    - name: Exibir tudo que veio dos playbooks anteriores
      debug:
        var: HEALTHCHECK

    - name: Montar dynamic_facts unificado de forma genérica
      set_stats:
        HEALTHCHECK: >-
          {{
            HEALTHCHECK | map('extract', attribute='title') | zip(HEALTHCHECK | map(attribute='value')) | 
            map('community.general.dict_kv', ['title', 'value']) | list
          }}

    - name: Renderizar o modelo do Adaptive Card
      template:
        src: templates/adaptive_card_healthcheck.json.j2
        dest: /tmp/adaptive_card_healthcheck.json

    - name: Enviar ao Teams
      uri:
        url: "{{ webhook_url }}"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body: "{{ lookup('file', '/tmp/adaptive_card_healthcheck.json') | from_json }}"
