- name: Montar Card e Enviar ao Teams
  hosts: localhost
  gather_facts: no

  tasks:
        
    - name: Capturar todas as variáveis do workflow
      set_fact:
        all_vars: "{{ hostvars['localhost'] | dict2items }}"

    - name: Exibir HEALTHCHECK final
      debug:
        msg: 
          Imprimindo all_vars: "{{ all_vars }}"
        

    - name: Filtrar apenas as variáveis de healthcheck
      set_fact:
        healthcheck_lists: >-
          {{
            all_vars
            | selectattr('key', 'search', '^HEALTHCHECK_')
            | map(attribute='value')
            | list
          }}

    - name: Concatenar todos os healthchecks
      set_fact:
        HEALTHCHECK: "{{ healthcheck_lists | sum(start=[]) }}"


    - name: Renderizar o modelo do Adaptive Card
      template:
        src: templates/adaptive_card_healthcheck.json.j2
        dest: /tmp/adaptive_card_healthcheck.json

    - name: Enviar ao Teams
      uri:
        url: "{{ webhook_url_msteams }}"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body: "{{ lookup('file', '/tmp/adaptive_card_healthcheck.json') | from_json }}"

